import React from 'react';
import Head from 'next/head'
const Footer = React.lazy(() => import('../components/Footer/Footer'))
import '../styles/globals.scss'
import Header from '../components/Header';
import MainPageLayout from '../layouts/MainPageLayout/';
import theme from '../store/theme';
import { observer } from 'mobx-react-lite';
import DarkMode from "../components/Eyes";

const MyApp = observer(({ Component, pageProps }) => {
  
  return (
    <>
      <Head>
        <title>Главная</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/tuvan_herb.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={true}></link>
      </Head>

      { theme.theme === 'dark' &&  (<DarkMode />) }

      <Component {...pageProps} />
    </>
  )
})

export default MyApp